[package]
name = "benchmark_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
gnuplot = "0.0.43"

[[bench]]
name = "my_benchmark"
harness = false
